version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./rabbitMq/etc/:/etc/rabbitmq/
      - ./rabbitMq/data/:/var/lib/rabbitmq/
      - ./rabbitMq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${COOKIE}
      RABBITMQ_DEFAULT_USER: ${USER}
      RABBITMQ_DEFAULT_PASS: ${USER_PASSWORD}
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${USER_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init/:/docker-entrypoint-initdb.d/
    networks:
      - app-network
    depends_on:
      - rabbitmq

  website:
    image: node:12-alpine
    container_name: website
    command: sh -c "yarn install && yarn serve"
    ports:
      - "8080:8080"
    working_dir: /website
    volumes:
      - ./website:/website
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - app-network

  server:
    image: node:12-alpine
    container_name: server
    working_dir: /server
    command:
      [
        "./wait-for",
        "rabbitmq:5672",
        "--",
        "sh",
        "-c",
        "yarn install && yarn start",
      ]
    volumes:
      - ./server:/server
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
