version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./rabbitMq/etc/:/etc/rabbitmq/
      - ./rabbitMq/data/:/var/lib/rabbitmq/
      - ./rabbitMq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: leo_cookie
      RABBITMQ_DEFAULT_USER: leo
      RABBITMQ_DEFAULT_PASS: leo_password
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "imbee_test"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "leo"
      # You can use whatever password you like
      MYSQL_PASSWORD: "leo_password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "imbee-test-leo"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init/:/docker-entrypoint-initdb.d/
    networks:
      - app-network
    

  website:
    image: node:12-alpine    
    container_name: website
    command: sh -c "yarn install && yarn serve"
    ports:
      - "8080:8080"
    working_dir: /website
    volumes:
      - ./website:/website
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - app-network
    
  server:
    image: node:12-alpine
    container_name: server
    command: sh -c "yarn install && yarn start"
    working_dir: /server
    volumes:
      - ./server:/server
    depends_on:
      - rabbitmq
      - mysql
      - website
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  
      
