version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./rabbitMq/etc/:/etc/rabbitmq/
      - ./rabbitMq/data/:/var/lib/rabbitmq/
      - ./rabbitMq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: leo_cookie
      RABBITMQ_DEFAULT_USER: leo
      RABBITMQ_DEFAULT_PASS: leo_password
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "fcm_job"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "leo"
      # You can use whatever password you like
      MYSQL_PASSWORD: "leo_password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "imbee-test-leo"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init/:/docker-entrypoint-initdb.d/
      
