version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "fcm_job"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "leo"
      # You can use whatever password you like
      MYSQL_PASSWORD: "leo_password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "imbee-test-leo"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init/:/docker-entrypoint-initdb.d/
